services:
  nginx:
    image: nginx
    container_name: $APP_NAME-nginx
    restart: always
    command: ['nginx', '-g', 'daemon off;']
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - v2
  api:
    build: ..
    image: $APP_NAME-v2:$APP_VERSION
    container_name: $APP_NAME-v2
    restart: always
    environment:
      - EXPORTER_SERVICE=http://exporter:8080
      - SWAGGER_SERVICE=http://swagger:8090
    env_file:
      - v2.env
    volumes:
      - type: bind
        source: $DATA/v2/data.db
        target: /pb/data.db
    expose:
      - 8090
    networks:
      - v2
  exporter:
    build:
      context: ..
      dockerfile: services/exporter/Dockerfile
    image: $APP_NAME-v2-exporter:1
    container_name: $APP_NAME-v2-exporter
    volumes:
      - type: bind
        source: $DATA/v2/data.db
        target: /pb/pb_data/data.db
    environment:
      - EXPORTER_PORT=8080
    expose:
      - 8080
    networks:
      - v2
    depends_on:
      - api
  swagger:
    build:
      context: ..
      dockerfile: services/swagger/Dockerfile
    image: $APP_NAME-v2-swagger:1
    container_name: $APP_NAME-v2-swagger
    environment:
      - PB_SERVICE=http://api:8090
      - SWAGGER_PORT=8090
    expose:
      - 8090
    networks:
      - v2
    depends_on:
      - api
networks:
  v2:
    name: $APP_NAME-v2
    driver: bridge

